### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by callmekatootie** [Yup-io/yup_docs#25]
I am looking at deploying the docs locally and I can't figure out how to deploy the gitbook.

Whenever I try an `npm install` I get an error about EINTEGRITY:

```
npm ERR! code EINTEGRITY
npm ERR! sha512-8ZItLHeEgaqEvd5lYBXfm4EZSFCX29Jb9K+lAHhDKzReKBQKj3R+7NOF6tjqYi9t4oI8VUfaWITJQm86wnXGNQ== integrity checksum failed when using sha512: wanted sha512-8ZItLHeEgaqEvd5lYBXfm4EZSFCX29Jb9K+lAHhDKzReKBQKj3R+7NOF6tjqYi9t4oI8VUfaWITJQm86wnXGNQ== but got sha512-WRoDn//mXBiJ1H40rqa3vH0toePwSsGb45iInWlTySa+Uu4k3tYUSxa2v1KqAiLtvlrSzaExqS1gtk96A9zvEA==. (2962 bytes)
```

I then deleted the package-lock.json file and tried again and ran into another issue:

```
> docsify-tabs@1.1.2 build /redacted/yup_docs
> rollup -c


/redacted/yup_docs/src/js/index.js → dist/docsify-tabs.js...
[!] (eslint plugin) Error: No ESLint configuration found.
src/js/index.js
Error: No ESLint configuration found.
```

Is this hosted on the gitkeep cloud instead and cannot be deployed locally?

**Comment by andrei0x309** [comment]
Sorry for the late response.

GitBook has deprecated local deployment, you can easily deploy any GitBook repo using the GitBook website, which allows you to sync with any branch/commit from a git repo without needing for local deployment.
